#### GetRawVotes
POST http://localhost:3000/customer/api/report/rawvotes/search
content-type: application/json

{
    "langId": null,
    "customerId": "EDL-C2019100003",
    "beginDate": "2019-10-01",
    "endDate": "2019-11-01",
    "qsetId": "QS00001",
    "qSeq": 3
}

#### GetRawVotes 2
POST http://localhost:3000/customer/api/report/rawvotes/search
content-type: application/json

{
    "langId": null,
    "customerId": "EDL-C2019100003",
    "beginDate": "2019-10-01",
    "endDate": "2019-11-01",
    "qsetId": "QS00001",
    "slides": [
        { "qSeq": 3 }
    ],
    "orgId": null
}