### Save vote (random generate)
POST http://localhost:3000/dev/api/votes/save
content-type: application/json

{
    "customerId": "EDL-C2019100004",
    "qSetId": "QS00004",
    "beginDate": "2020-01-14",
    "endDate": "2020-01-14",
    "sampleSize": 15
}
